version: '3'

services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: top-heroes
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
