version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: top-heroes
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: top_heroes
      MYSQL_USER: root
      MYSQL_PASSWORD: SuperSecretPasswordOneTwoThree!
      MYSQL_PORT: 3306


  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPasswordOneTwoThree!
      MYSQL_DATABASE: top_heroes
      MYSQL_USER: top_heroes
      MYSQL_PASSWORD: top_heroes
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql_data:
    
networks:
  app-network:
    driver: bridge
